"""Sync opcion_pago column with contact table

Revision ID: 2158fae6c883
Revises: cbae5ce2acf2
Create Date: 2024-07-03 23:19:52.873926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2158fae6c883'
down_revision = 'cbae5ce2acf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opcion_pago', sa.Text(), nullable=True))
        batch_op.drop_column('opcion de Pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opcion de Pago', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('opcion_pago')

    # ### end Alembic commands ###
