"""Añadido campo documento al modelo Contact

Revision ID: cbae5ce2acf2
Revises: 
Create Date: 2024-07-02 23:47:33.034506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbae5ce2acf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.String(length=12), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('consulta',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('nacionalidad',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('sexo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('nacionalidad',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('consulta',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('documento')

    # ### end Alembic commands ###
